### ISSUE TITLE
Dúvida quanto ao inventário

### ISSUE THREAD

**Issue by hemersonpinheiro** [duartejr/pyHidroWeb#1]
após escolher o arquivo csv com as estações é solicitado o arquivo com o inventario, também em formato csv. Porém a ANA oferece o inventário em formato mdb. Como posso resolver isso?

**Comment by duartejr** [comment]
Você deverá exportar o iventário em formato csv. É possível fazer isto através do Microsoft Acccess.

**Comment by LuiskH** [comment]
Estou utilizando a aplicação no Linux.
Tive problemas com entender qual era o inventário, logo de entnder e dar algumas modificações no código surgiu um erro relacionado ao geckodriver. 
Depois de resolver esse problema o codigo roda, porém não descarrega os arquivos, dei algumas modificações no webdriver, mas, continua não descarregando. 
Como posso solucionar isso?
Obrigado!!!

**Comment by duartejr** [comment]
O Hidroweb não permite mais download de dados automatizado usandos bots como esse script. Qualquer tentativa de download automático dos dados será bloqueada. O sistema agora exige a verificação por imagens.

**Comment by LuiskH** [comment]
Certo! Obrigado pela resposta!!
