### ISSUE TITLE
problemas com importação a parti do shape file. 

### ISSUE THREAD

**Issue by ibpablo** [duartejr/pyHidroWeb#2]
Prezado, estou tentando executar o código para baixar dados dentro de uma área de interesse.  No entanto ao executar a opção de escolher a pasta de saída, o seguinte erro aparece:
ValueError: Usecols do not match columns, columns expected but not found: ['Latitude', 'Longitude', 'Nome', 'Codigo', 'TipoEstacao']

Durante o processo, é pedido o arquivo csv do inventario das estações. Para isso, é necessário exportar o arquivo 'Estações" de dentro do banco de dados que a hidroweb disponibiliza no formato mdb? Nesta tentativa, avancei. No entanto o erro ainda aparece. 

Obrigado!

**Comment by duartejr** [comment]
O portal Hidroweb têm mudado constantemente é difícil mantêr o script atualizado. A algum tempo havia sido implementado um recurso para verificação de bots, o que impede o uso deste script. Mas no seu caso o erro deve estar no momento da exportação do arquivo .csv. Na exportação é necessário manter o título das colunas. No seu caso, aparentemente, na hora da exportação foi removido o título das colunas, ou mudados.
